source 'https://gitee.com/moduless/hfmo-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'HFMoMain_Example' do
  pod 'HFMoMain', :path => '../'

  target 'HFMoMain_Tests' do
    inherit! :search_paths

    
  end
end
